version: 2
updates:
  - package-ecosystem: npm
    directories:
      - "/"
      - "/src-admin"
    schedule:
      interval: monthly
      time: "00:05"
      timezone: Europe/Berlin
    open-pull-requests-limit: 20
    assignees:
      - simpros
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "00:05"
      timezone: Europe/Berlin
    open-pull-requests-limit: 20
    assignees:
      - simpros
