# Dependabot will run on day 11 of each month at 02:06 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: 'npm'
    directories:
      - '**/*'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '04:17'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 20
    assignees:
      - 'simpros'
    versioning-strategy: 'increase'
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '04:42'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 20
    assignees:
      - 'simpros'
